SpMarket/SpMarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from sp_goods.views import index

urlpatterns = [
    url(r'^$', index),#网站的首页
    url(r'^admin/', admin.site.urls),#后台管理的路由
    # 上传部件自动调用的上传地址
    # 全文搜索框架
    url(r'^search/', include('haystack.urls')),
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    url(r'^user/', include("sp_user.urls", namespace="sp_user")),  # 用户模块
    url(r'^goods/', include("sp_goods.urls", namespace="sp_goods")),  # 商品模块
    url(r'^cart/', include("sp_cart.urls", namespace="sp_cart")),  # 购物车模块
    url(r'^order/', include("sp_order.urls", namespace="sp_order")),  # 订单模块
]

SpMarket/apps/sp_user/urls.py
from django.conf.urls import url
from sp_user.views import (LoginView,
                           RegisterView,
                           ForgetPassView,
                           MemeberView,
                           InfomationView,
                           send_msg_phone,
                           AddressView,
                           AddressAddView,
                           AddressEditView,
                           delAddress)

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),  # 登陆
    url(r'^register/$', RegisterView.as_view(), name="register"),  # 注册
    url(r'^forget/$', ForgetPassView.as_view(), name="forget"),  # 忘记密码
    url(r'^member/$', MemeberView.as_view(), name="member"),  # 个人中心
    url(r'^info/$', InfomationView.as_view(), name="info"),  # 个人资料
    url(r'^sendMsg/$', send_msg_phone, name="sendMsg"),  # 短信地址
    url(r'^address/$', AddressView.as_view(), name="address"),  # 收货地址首页
    url(r'^address/add/$', AddressAddView.as_view(), name="address_add"),  # 收货地址添加
    url(r'^address/edit/(?P<id>\d+)/$', AddressEditView.as_view(), name="address_edit"),  # 收货地址编辑
    url(r'^address/del/$', delAddress, name="address_del"),  # 收货地址删除
]

SpMarket/apps/sp_user/forms.py
from django import forms

from sp_user.helper import set_password
from sp_user.models import SpUser, SpAddress
from django_redis import get_redis_connection

"""
    普通的form
    
    
    modelform

"""


class RegisterModelForm(forms.ModelForm):
    """注册表单, 验证"""
    # 单独添加字段
    password1 = forms.CharField(max_length=16,
                                min_length=6,
                                error_messages={
                                    'required': '密码必填',
                                    'max_length': '密码长度不能大于16个字符',
                                    'min_length': '密码长度必须大于6个字符',
                                }
                                )
    password2 = forms.CharField(error_messages={'required': "确认密码必填"})

    verify_code = forms.CharField(error_messages={"required": "验证码必填!"})

    class Meta:
        model = SpUser
        # 需要验证的字段
        fields = ['phone', ]

        error_messages = {
            "phone": {
                "required": "手机号码必须填写!"
            }
        }

    # 单独清洗(验证)
    def clean_password2(self):
        # 验证两个密码是否一致
        pwd1 = self.cleaned_data.get('password1')
        pwd2 = self.cleaned_data.get('password2')

        if pwd1 and pwd2 and pwd1 != pwd2:
            # 确认密码错误
            raise forms.ValidationError("两次密码输入不一致!")
        return pwd2

    def clean_phone(self):
        # 验证手机号码是否唯一
        phone = self.cleaned_data.get('phone')
        rs = SpUser.objects.filter(phone=phone).exists()  # 返回bool
        if rs:
            raise forms.ValidationError("手机号码已经被注册")
        return phone

    # 单独验证验证
    def clean_verify_code(self):
        # 获取用户表单提交的
        phone = self.cleaned_data.get("phone")
        verify_code = self.cleaned_data.get('verify_code')
        # 获取redis中的
        r = get_redis_connection("default")
        if phone:
            # 获取 redis中获取的值 是二进制编码,必须解码
            code = r.get(phone)
            code = code.decode("utf-8")
            if code is None:
                raise forms.ValidationError("验证码已经过期或者错误!")
            # 比对
            if verify_code != code:
                raise forms.ValidationError("验证码填写错误!")

            # 最后返回当前字段清洗后的结果
            return verify_code
        else:
            return verify_code


class LoginModelForm(forms.ModelForm):
    """登陆的form表单"""

    class Meta:
        model = SpUser
        fields = ['phone', 'password']

        error_messages = {
            'phone': {
                "required": "手机号码必须填写!"
            },
            'password': {
                "required": "密码必须填写!"
            }
        }

        widgets = {  # 样式
            'phone': forms.TextInput(attrs={"class": "login-name", "placeholder": '请输入手机号'}),
            'password': forms.PasswordInput(attrs={"class": "login-password", "placeholder": '请输入密码'}),
        }

    def clean(self):  # 综合校验
        cleaned_data = self.cleaned_data
        # 获取用手机和密码
        phone = cleaned_data.get('phone')
        password = cleaned_data.get('password')
        # 验证手机号码是否存在
        if all([phone, password]):
            # 根据手机号码获取用户
            try:
                user = SpUser.objects.get(phone=phone)
            except SpUser.DoesNotExist:
                raise forms.ValidationError({"phone": "该用户不存在!"})

            # 判断密码是否正确
            if user.password != set_password(password):
                raise forms.ValidationError({"password": "密码填写错误!"})

            # 正确
            # 将用户信息保存到cleaned_data中
            cleaned_data['user'] = user
            return cleaned_data
        else:
            return cleaned_data


class InfoModelForm(forms.ModelForm):
    class Meta:
        model = SpUser
        fields = ['nickname', 'head', 'birth_of_date']

        # error_messages


class AddressModelForm(forms.ModelForm):
    class Meta:
        model = SpAddress
        fields = ['hcity', 'hproper', 'harea', 'detail', 'username', 'phone', 'isDefault']

        error_messages = {
            "harea": {
                "required": "收货地址必填"
            },
            "detail": {
                "required": "详细地址必填"
            },
            "phone": {
                "required": "手机号码必填"
            },
            "username": {
                "required": "收货人姓名必填"
            },
        }

    def clean(self):
        # 验证当前用户的收货地址的数量,如果超过6个就报错
        user_id = self.data.get('user_id')
        count = SpAddress.objects.filter(user_id=user_id, isDelete=False).count()
        if count >= 6:
            raise forms.ValidationError("收货地址数量不能超过6")

        # 默认收货地址只能有一个, 判断当前添加的是否 isDefault==True,
        # 如果是就讲其他的收货地址都设置为False
        isDefault = self.cleaned_data.get("isDefault")
        if isDefault:
            # 如果是就讲其他的收货地址都设置为False
            SpAddress.objects.filter(user_id=user_id).update(isDefault=False)

        return self.cleaned_data


class AddressEditModelForm(forms.ModelForm):
    class Meta:
        model = SpAddress
        fields = ['hcity', 'hproper', 'harea', 'detail', 'username', 'phone', 'isDefault']

        error_messages = {
            "harea": {
                "required": "收货地址必填"
            },
            "detail": {
                "required": "详细地址必填"
            },
            "phone": {
                "required": "手机号码必填"
            },
            "username": {
                "required": "收货人姓名必填"
            },
        }

    def clean(self):
        # 验证当前用户的收货地址的数量,如果超过6个就报错
        user_id = self.data.get('user_id')

        # 默认收货地址只能有一个, 判断当前添加的是否 isDefault==True,
        # 如果是就讲其他的收货地址都设置为False
        isDefault = self.cleaned_data.get("isDefault")
        if isDefault:
            # 如果是就讲其他的收货地址都设置为False
            SpAddress.objects.filter(user_id=user_id).update(isDefault=False)

        return self.cleaned_data

SpMarket/apps/sp_user/views.py
import random
import uuid

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View

from db.base_view import BaseVerifyView
from sp_user.forms import RegisterModelForm, LoginModelForm, AddressModelForm, AddressEditModelForm
from sp_user.helper import set_password, login, verify_login, send_sms
from sp_user.models import SpUser, SpAddress
import re
from django_redis import get_redis_connection

"""
    开始定义视图:
    1. 函数
    2. 视图类
        a. 定义一个类, 继承 View
        b. 定义方法, 方法名一定要和请求方式名同名(小写 get,post)
        c. 所有的方法都第一个参数和第二个都是固定: self,request
"""


class LoginView(View):
    """登陆"""

    def get(self, request):
        # 创建登陆表单对象
        login_form = LoginModelForm()
        return render(request, "sp_user/login.html", {'form': login_form})

    def post(self, request):
        # 接收数据
        data = request.POST
        # 验证数据
        login_form = LoginModelForm(data)
        if login_form.is_valid():
            # 验证成功后将登陆标识放到session中
            user = login_form.cleaned_data.get('user')
            # 调用登陆的方法,放在helper模块中的
            login(request, user)

            # 判断链接上是否有参数next,如果有就跳转到指定的页面
            next = request.GET.get('next')
            if next:
                return redirect(next)
            else:
                # 跳转到用户中心页面
                return redirect('sp_user:member')
        else:
            return render(request, "sp_user/login.html", {'form': login_form})


@verify_login
def foo(request):
    pass


class RegisterView(View):
    """注册"""

    def get(self, request):
        return render(request, "sp_user/reg.html")

    def post(self, request):
        # 处理
        # 1. 接收
        data = request.POST
        # 2. 处理
        # 验证是否合法
        form = RegisterModelForm(data)
        if form.is_valid():
            # 处理,保存到数据库
            data = form.cleaned_data
            # 密码需要加密
            password = data.get('password2')
            # 调用方法帮助我对密码进行加密
            password = set_password(password)
            # 保存到数据库
            SpUser.objects.create(phone=data.get('phone'), password=password)

            # 成功跳转到登陆页面
            return redirect("sp_user:login")
        else:
            # 传递错误信息到页面
            context = {
                "errors": form.errors,
            }
            # 3. 响应
            return render(request, "sp_user/reg.html", context)


class ForgetPassView(View):
    """找回密码"""

    def get(self, request):
        return render(request, "sp_user/forgetpassword.html")

    def post(self, request):
        pass


class MemeberView(BaseVerifyView):
    """个人中心"""

    def get(self, request):
        context = {
            "phone": request.session.get('phone'),
            "head": request.session.get('head'),
        }
        return render(request, 'sp_user/member.html', context)

    def post(self, request):
        pass

    # # 视图类的装饰器
    # @method_decorator(verify_login)
    # def dispatch(self, request, *args, **kwargs):
    #     return super().dispatch(request, *args, **kwargs)


class InfomationView(BaseVerifyView):
    """个人资料"""

    def get(self, request):
        # 查询用户的个人信息 进行回显
        # session中保存了用户的id
        user_id = request.session.get("ID")

        # 根据用户id查询用户信息
        user = SpUser.objects.get(pk=user_id)

        # 渲染到页面
        context = {
            "user": user
        }
        return render(request, 'sp_user/infor.html', context)

    def post(self, request):
        # 获取当前用户对象
        user_id = request.session.get("ID")
        user = SpUser.objects.get(pk=user_id)
        user.nickname = request.POST.get("nickname")
        user.gender = request.POST.get("gender")
        # 文件字段
        user.head = request.FILES.get("head")
        user.birth_of_date = request.POST.get("birth_of_date")
        user.save()

        # 重写session
        login(request, user)

        # 跳转
        return redirect("sp_user:member")


def send_msg_phone(request):
    """发生短信的视图函数"""
    if request.method == "POST":
        # 接收到手机号码
        phone = request.POST.get("phone", "")
        # 后端验证手机号码格式是否正确
        # 创建正则对象
        phone_re = re.compile("^1[3-9]\d{9}$")
        # 匹配传入的手机号码
        rs = re.search(phone_re, phone)
        if rs is None:
            # 手机号码格式错误
            return JsonResponse({"err": 1, "errmsg": "手机号码格式错误!"})

        # 生成随机码 随机数字组成
        random_code = "".join([str(random.randint(0, 9)) for _ in range(4)])

        # 保存随机码到redis中
        # 使用redis, 获取redis连接
        r = get_redis_connection("default")
        # 直接开始操作
        r.set(phone, random_code)
        # 设置过期时间
        r.expire(phone, 120)

        # 发送短信
        print(random_code)
        # 使用阿里发生短信
        # __business_id = uuid.uuid1()
        # params = "{\"code\":\"%s\",\"product\":\"厚江小超\"}" % random_code
        # print(send_sms(__business_id, phone, "注册验证", "SMS_2245271", params))

        # 成功
        return JsonResponse({"err": 0})
    else:
        # 提示请求方式错误 json 格式
        return JsonResponse({"err": 1, "errmsg": "请求方式错误!"})


class AddressView(BaseVerifyView):
    """
        收货地址列表页
    """

    def get(self, request):
        # 获取收货地址,所有的, 当前用户的
        user_id = request.session.get("ID")
        # 查询
        addresses = SpAddress.objects.filter(user_id=user_id,isDelete=False).order_by("-isDefault")

        # 渲染数据
        context = {
            'addresses': addresses
        }
        return render(request, 'sp_user/gladdress.html', context)

    def post(self, request):
        pass


class AddressAddView(BaseVerifyView):
    """
        收货地址添加页
    """

    def get(self, request):
        return render(request, 'sp_user/address.html')

    def post(self, request):
        # 接收参数
        data = request.POST.dict()
        data['user_id'] = request.session.get("ID")
        # 验证参数
        form = AddressModelForm(data)
        # 处理数据
        if form.is_valid():
            # cleaned_data = form.cleaned_data
            # # cleaned_data['user'] = SpUser.objects.get(pk=request.session.get("ID"))
            # cleaned_data['user_id'] = request.session.get("ID")
            # SpAddress.objects.create(**cleaned_data)
            form.instance.user_id = request.session.get("ID")
            # modelform对象上有个save()方法,直接就能保存数据
            form.save()
            # 返回响应 返回收货地址列表页面
            return redirect("sp_user:address")
        else:
            context = {
                "form": form,
            }
            return render(request, "sp_user/address.html", context)


class AddressEditView(BaseVerifyView):
    """
        收货地址修改页
    """

    def get(self, request, id):
        # 查询当前用户的 当前id的收货地址
        user_id = request.session.get("ID")
        # 查询
        try:
            address = SpAddress.objects.get(user_id=user_id, pk=id)
        except SpAddress.DoesNotExist:
            return redirect("sp_user:address")

        # 渲染到页面
        context = {
            "address": address
        }

        return render(request, 'sp_user/address_edit.html', context)

    def post(self, request, id):
        # 接收数据
        data = request.POST.dict()
        # 验证数据
        user_id = request.session.get("ID")
        data['user_id'] = user_id
        form = AddressEditModelForm(data)
        # 处理数据
        if form.is_valid():
            # 更新 根据主键id
            cleaned_data = form.cleaned_data
            id = data.get('id')
            SpAddress.objects.filter(user_id=user_id, pk=id).update(**cleaned_data)

            # 跳转
            return redirect("sp_user:address")
        else:
            # 返回响应
            context = {
                "form": form,
                "address": data
            }
            return render(request, 'sp_user/address_edit.html', context)


def delAddress(request):
    """删除收货地址"""
    if request.method == "POST":
        # 必须登陆
        user_id = request.session.get('ID')
        id = request.POST.get("id")
        if user_id is None:
            return JsonResponse({"code": 1, "errmsg": "没有登陆!"})
        # 删除的时候最好 用户的id条件加上
        SpAddress.objects.filter(user_id=user_id, pk=id).update(isDelete=True)
        # 返回结果
        return JsonResponse({"code": 0})
    else:
        return JsonResponse({"code": 2,"errmsg":"请求方式错误"})

SpMarket/templates/sp_user/forgetpassword.html
{% extends 'public/base.html' %}
{% load static %}

{% block header_title %}
<a href="" class="">忘记密码</a>
{% endblock %}


{% block content %}
<input type="text" name="mobile"  placeholder="请输入手机号" class="login-password">
	    <div class="yzm">
	    	<input type="text" class="reg-yzm" placeholder="输入验证码" />
	    	<input type="button" class="yzm-hq" value="获取验证码" />
	    </div>
	    <input type="password" name="password"  placeholder="请输入密码" class="login-password">
	    <input type="password" name="password"  placeholder="确认密码" class="login-name">
	    <input type="button" class="login-btn" value="立即提交">
{% endblock %}

SpMarket/templates/sp_user/gladdress.html
{% extends 'public/base.html' %}
{% load static %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">管理收货地址</a>
        </h1>
        <div class="am-header-right am-header-nav">
            <a href="{% url 'sp_user:address_add' %}" class="">
                <i class="am-icon-plus"></i>
            </a>
        </div>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <ul class="address-list">
        {% for address in addresses %}
            <li data-id="{{ address.pk }}" {% if address.isDefault %}class="curr"{% endif %}>
                <p>收货人：{{ address.username }}&nbsp;&nbsp;{{ address.phone }}</p>
                <p class="order-add1">收货地址：
                    {{ address.hcity }}
                    {{ address.hproper }}
                    {{ address.harea }}
                    {{ address.detail }}
                </p>
                <hr/>
                <div class="address-cz">
                    <label class="am-radio am-warning">
                        <input type="radio" name="radio3" data-am-ucheck {% if address.isDefault %}
                               checked
                        {% endif %}> 设为默认
                    </label>
                    <a href="{% url 'sp_user:address_edit' address.pk %}"><img src="{% static 'images/bj.png' %}" width="18"/>编辑</a>
                    <a href="javascript:;" class="del">删除</a>
                </div>
            </li>
        {% endfor %}
    </ul>
{% endblock %}


{% block footer_js %}
<script>
    $(function () {
        //绑定删除
        $(".del").on("click",function () {
            //ajax发起删除
            //准备数据
            var li = $(this).parents("li");
            var id = li.attr("data-id");
            //发送ajax
            $.ajax({
                type:"post",
                url:"{% url 'sp_user:address_del' %}",
                data:{
                    "id":id,
                    "csrfmiddlewaretoken":"{{ csrf_token }}"
                },
                dataType:"json",
                success:function (data) {
                    if(data.code == 0){
                        li.remove();
                    }else {
                        alert("删除失败!");
                    }
                }
            })
        })
    })
</script>
{% endblock %}

SpMarket/templates/sp_user/login.html
{% extends 'public/base.html' %}

{% load static %}

{% block meta_title %}
    超市
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">登录</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}


{% block content %}
    <form action="" method="post" novalidate>
        <div style="height: 3rem;"></div>
        {% csrf_token %}
        {{ form.phone }}<p class="am-text-danger">{{ form.errors.phone.0 }}</p>
        {{ form.password }}<p class="am-text-danger">{{ form.errors.password.0 }}</p>
        <input type="submit" class="login-btn" value="我要登录">
    </form>
    <div class="agree">
        <a href="{% url 'sp_user:register' %}">免费注册</a>
        <a href="{% url 'sp_user:forget' %}" class="forget">忘记密码？</a>
    </div>
    <div class="line"></div>
    <div class="line-text">第三方账号登录</div>
    <ul class="second-login">
        <li><a href=""><img src="{% static 'images/wxlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/qqlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/sinalog.png' %}"/></a></li>
    </ul>
{% endblock %}

SpMarket/templates/sp_user/member.html
{% extends 'public/base.html' %}
{% load static %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <h1 class="am-header-title">
            <a href="" class="">个人中心</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}


{% block content %}
    <div class="member">
        <div class="mem-tit">{{ phone }}
            <a href="step.html" class="step"><img src="{% static 'images/step.png' %}" width="26"/></a>
        </div>
        <div class="mem-pic">
            <div class="mem-pic-bg" style="background-image: url({{ MEDIA_URL }}{{ head }});"></div>
        </div>
        <ul class="member-menu">
            <li>
                <a href="records.html">
                    <p class="yellow">0</p>
                    <p class="black">帐户余额 </p>
                </a>
            </li>
            <li>
                <a href="integral.html">
                    <p class="yellow">0</p>
                    <p class="black">积分 </p>
                </a>
            </li>
            <li>
                <a href="yhq.html">
                    <p class="yellow">0</p>
                    <p class="black">优惠劵 </p>
                </a>
            </li>
            <li>
                <a href="collect.html">
                    <p class="yellow">0</p>
                    <p class="black">我的收藏 </p>
                </a>
            </li>
        </ul>
    </div>
    <div class="user-list">
        <div class="u-list-main">
            <img src="{% static 'images/order-pic.png' %}" width="27"/>
            <span>我的购物订单</span>
            <a href="allorder.html">查看全部订单></a>
        </div>
        <ul class="user-nav">
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon.png' %}">
                <p>待付款</p></a></li>
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon1.png' %}">
                <p>待收货</p></a></li>
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon2.png' %}">
                <p>待评价</p></a></li>
            <li><a href="allorder.html"> <img src="{% static 'images/1-icon3.png' %}">
                <p>退换货</p></a></li>
        </ul>
        <div class="u-list-main">
            <img src="{% static 'images/order-my.png' %}" width="27"/>
            <span>帐户与安全</span>
        </div>
        <ul class="user-nav">
            <li><a href="{% url 'sp_user:info' %}"> <img src="{% static 'images/1-icon4.png' %}">
                <p>个人资料</p></a></li>
            <li><a href="{% url 'sp_user:address' %}"> <img src="{% static 'images/1-icon5.png' %}">
                <p>收货地址</p></a></li>
            <li><a href="saftystep.html"> <img src="{% static 'images/1-icon6.png' %}">
                <p>安全设置</p></a></li>
            <li><a href="money.html"> <img src="{% static 'images/1-icon7.png' %}">
                <p>我的钱包</p></a></li>
        </ul>
    </div>
    <!--导航-->
    <ul class="sq-nav"
        style=" background: #fff; margin-top: 1rem; border-top: 1px solid #ddd;  border-bottom: 1px solid #ddd;">
        <li>
            <div class="am-gallery-item">
                <a href="job.html" class="">
                    <img src="{% static 'images/m_03.png' %}"/>
                    <p>我要兼职</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="recommend.html" class="">
                    <img src="{% static 'images/m_04.png' %}"/>
                    <p>推荐有奖</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="myrecommend.html" class="">
                    <img src="{% static 'images/m_05.png' %}"/>
                    <p>我的推荐</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/m_06.png' %}"/>
                    <p>我的佣金</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="yhq.html" class="">
                    <img src="{% static 'images/m_02.png' %}"/>
                    <p>我的红包</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="message.html" class="">
                    <img src="{% static 'images/m_07.png' %}"/>
                    <p>我的动态</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:;" class="index-qd">
                    <img src="{% static 'images/m_08.png' %}"/>
                    <p>客服中心</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/m_09.png' %}"/>
                    <p>安全退出</p>
                </a>
            </div>
        </li>
    </ul>
    </div>
    <!--客服中心-->
    <div class="qd-box">
        <div class="popup-title">
            <span>客服中心</span>
            <div class="popup-close"><i class="iconfont">&#xe602</i></div>
        </div>
        <div class="dq-text">
            <a href="http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes">
                <img src="{% static 'images/contactqq.png' %}" width="50"/>
                <p class="contactqq">联系QQ</p>
            </a>
            <a href="tel:0791-12345678">
                <img src="{% static 'images/contacttele.png' %}" width="50"/>
                <p class="contacttele">呼叫电话</p>
            </a>
        </div>
    </div>
    <!--客服中心-->
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="index.html" class="">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="shopcart.html" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="allorder.html" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="member.html" class="curr">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}
 