SpMarket/SpMarket/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from sp_goods.views import index

urlpatterns = [
    url(r'^$', index),#网站的首页
    url(r'^admin/', admin.site.urls),#后台管理的路由
    # 上传部件自动调用的上传地址
    # 全文搜索框架
    url(r'^search/', include('haystack.urls')),
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    url(r'^user/', include("sp_user.urls", namespace="sp_user")),  # 用户模块
    url(r'^goods/', include("sp_goods.urls", namespace="sp_goods")),  # 商品模块
    url(r'^cart/', include("sp_cart.urls", namespace="sp_cart")),  # 购物车模块
    url(r'^order/', include("sp_order.urls", namespace="sp_order")),  # 订单模块
]

SpMarket/apps/sp_cart/urls.py
from django.conf.urls import url

from sp_cart.views import AddCartView, ShopCartView

urlpatterns = [
    url(r'^addCart/$', AddCartView.as_view(), name="addCart"),
    url(r'^$', ShopCartView.as_view(), name="index"),
]

SpMarket/apps/sp_goods/urls.py
from django.conf.urls import url

from sp_goods.views import index, category, detail

urlpatterns = [
    url(r'^$', index, name="首页"),
    url(r'^category/(?P<cate_id>\d+)/(?P<order>\d)/$', category, name="分类"),
    url(r'^(?P<id>\d+).html$', detail, name="详情"),
]

SpMarket/apps/sp_user/urls.py
from django.conf.urls import url
from sp_user.views import (LoginView,
                           RegisterView,
                           ForgetPassView,
                           MemeberView,
                           InfomationView,
                           send_msg_phone,
                           AddressView,
                           AddressAddView,
                           AddressEditView,
                           delAddress)

urlpatterns = [
    url(r'^login/$', LoginView.as_view(), name="login"),  # 登陆
    url(r'^register/$', RegisterView.as_view(), name="register"),  # 注册
    url(r'^forget/$', ForgetPassView.as_view(), name="forget"),  # 忘记密码
    url(r'^member/$', MemeberView.as_view(), name="member"),  # 个人中心
    url(r'^info/$', InfomationView.as_view(), name="info"),  # 个人资料
    url(r'^sendMsg/$', send_msg_phone, name="sendMsg"),  # 短信地址
    url(r'^address/$', AddressView.as_view(), name="address"),  # 收货地址首页
    url(r'^address/add/$', AddressAddView.as_view(), name="address_add"),  # 收货地址添加
    url(r'^address/edit/(?P<id>\d+)/$', AddressEditView.as_view(), name="address_edit"),  # 收货地址编辑
    url(r'^address/del/$', delAddress, name="address_del"),  # 收货地址删除
]

SpMarket/apps/sp_goods/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from db.base_model import BaseModel
from django.conf import settings

is_on_sale_choices = (
    (False, "下架"),
    (True, "上架"),
)


class Category(BaseModel):
    """
        商品分类
    """
    cate_name = models.CharField(verbose_name='分类名称',
                                 max_length=20
                                 )
    brief = models.CharField(verbose_name='描述',
                             max_length=200,
                             null=True,
                             blank=True
                             )
    order = models.SmallIntegerField(default=0, verbose_name="排序")

    def __str__(self):
        return self.cate_name

    class Meta:
        verbose_name = "商品分类管理"
        verbose_name_plural = verbose_name


class Unit(BaseModel):
    """
        商品SKU_单位
    """
    name = models.CharField(max_length=20,
                            verbose_name="单位")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "商品单位管理"
        verbose_name_plural = verbose_name


class GoodsSPU(BaseModel):
    """
        商品SPU表
    """
    spu_name = models.CharField(verbose_name='商品SPU名称',
                                max_length=20,
                                )
    # RichTextUploadingField 使用富文本编辑器渲染之前的普通文本框
    content = RichTextUploadingField(verbose_name="商品详情")

    def __str__(self):
        return self.spu_name

    class Meta:
        verbose_name = "商品SPU"
        verbose_name_plural = verbose_name


class GoodsSKU(BaseModel):
    """
        商品SKU表
    """

    sku_name = models.CharField(verbose_name='商品SKU名称',
                                max_length=100,
                                )
    brief = models.CharField(verbose_name="商品的简介",
                             max_length=200,
                             null=True,
                             blank=True,
                             )
    price = models.DecimalField(verbose_name='价格',
                                max_digits=9,
                                decimal_places=2,
                                default=0,
                                )
    unit = models.ForeignKey(to="Unit", verbose_name="单位")

    stock = models.IntegerField(verbose_name='库存',
                                default=0)

    sale_num = models.IntegerField(verbose_name='销量',
                                   default=0)

    # 默认相册中的第一张图片作为封面图片
    logo = models.ImageField(verbose_name='封面图片',
                             upload_to='goods/%Y%m/%d'
                             )

    # 自定义的字段
    def show_logo(self):
        return "<img style='width:80px' src='{}{}'/>".format(settings.MEDIA_URL, self.logo)

    show_logo.allow_tags = True
    show_logo.short_description = "LOGO"

    is_on_sale = models.BooleanField(verbose_name="是否上架",
                                     choices=is_on_sale_choices,
                                     default=0)
    category = models.ForeignKey(to="Category",
                                 verbose_name='商品分类',
                                 )

    goods_spu = models.ForeignKey(to="GoodsSPU", verbose_name="商品SPU")

    def __str__(self):
        return self.sku_name

    class Meta:
        verbose_name = "商品SKU管理"
        verbose_name_plural = verbose_name


class Gallery(BaseModel):
    """
       商品相册
    """
    img_url = models.ImageField(verbose_name='相册图片地址',
                                upload_to='goods_gallery/%Y%m/%d'
                                )

    goods_sku = models.ForeignKey(to="GoodsSKU", verbose_name="商品SKU")

    class Meta:
        verbose_name = "商品相册管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return "商品相册"


class Banner(BaseModel):
    """
        首页轮播
    """
    name = models.CharField(verbose_name="轮播活动名",
                            max_length=150,
                            )
    img_url = models.ImageField(verbose_name='轮播图片地址',
                                upload_to='banner/%Y%m/%d'
                                )
    order = models.SmallIntegerField(verbose_name="排序",
                                     default=0,
                                     )

    goods_sku = models.ForeignKey(to="GoodsSKU", verbose_name="商品SKU")

    class Meta:
        verbose_name = "轮播管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Activity(BaseModel):
    """
        首页活动
    """
    title = models.CharField(verbose_name='活动名称', max_length=150)
    img_url = models.ImageField(verbose_name='活动图片地址',
                                upload_to='activity/%Y%m/%d'
                                )
    url_site = models.URLField(verbose_name='活动的url地址', max_length=200)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "活动管理"
        verbose_name_plural = verbose_name


class ActivityZone(BaseModel):
    """
        首页活动专区
    """
    title = models.CharField(verbose_name='活动专区名称', max_length=150)
    brief = models.CharField(verbose_name="活动专区的简介",
                             max_length=200,
                             null=True,
                             blank=True,
                             )
    order = models.SmallIntegerField(verbose_name="排序",
                                     default=0,
                                     )
    is_on_sale = models.BooleanField(verbose_name="上否上线",
                                     choices=is_on_sale_choices,
                                     default=0,
                                     )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "活动专区管理"
        verbose_name_plural = verbose_name


class ActivityZoneGoods(BaseModel):
    """
        首页活动专区商品列表
    """
    zone = models.ForeignKey(to="ActivityZone", verbose_name="活动专区")
    goods_sku = models.ForeignKey(to="GoodsSKU", verbose_name="商品SKU")

SpMarket/apps/sp_goods/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect

from sp_goods.models import (GoodsSKU,
                             Banner,
                             Activity,
                             ActivityZone,
                             Category)

from django_redis import get_redis_connection

def index(request):
    """首页"""
    # 获取轮播
    banners = Banner.objects.filter(isDelete=False).order_by("-order")

    # 获取活动
    acts = Activity.objects.filter(isDelete=False)

    # 获取特色专区
    act_zones = ActivityZone.objects.filter(is_on_sale=True, isDelete=False).order_by("-order")

    # 渲染数据
    context = {
        "banners": banners,
        "acts": acts,
        "act_zones": act_zones,
    }

    return render(request, "sp_goods/index.html", context)


def category(request, cate_id, order):
    """
        综合,销量,价格,新品 排序规则需要程序员自己去定义参数,并且规定参数的含义

        0 综合
        1 销量
        2 价格降
        3 价格升
        4 新品

        定义一个列表:["id","-sale_num","-price","price","-add_time"]
    """
    # 类型转成整数
    try:
        cate_id = int(cate_id)
        order = int(order)
    except:
        return redirect("sp_goods:首页")

    # 所有的分类 产品经理
    categorys = Category.objects.filter(isDelete=False).order_by("-order")

    # 查询某个分类下的所有商品
    # 默认查询第一个分类
    if cate_id == 0:
        category = categorys.first()
        cate_id = category.pk

    goodsSkus = GoodsSKU.objects.filter(is_on_sale=True, isDelete=False, category_id=cate_id)
    # if order == 0:
    #     goodsSkus = goodsSkus
    # elif order == 1:
    #     goodsSkus = goodsSkus.order_by("-sale_num")
    # elif order == 2:
    #     goodsSkus = goodsSkus.order_by("-price")
    # elif order == 3:
    #     goodsSkus = goodsSkus.order_by("price")
    # elif order == 4:
    #     goodsSkus = goodsSkus.order_by("-add_time")

    order_rule = ["id", "-sale_num", "-price", "price", "-add_time"]
    try:
        order_one = order_rule[order]
    except:
        order_one = order_rule[0]
        order = 0
    goodsSkus = goodsSkus.order_by(order_one)

    # 对数据进行分页
    pageSize = 10
    paginator = Paginator(goodsSkus,pageSize)

    # 获取某页数据
    p = request.GET.get('p',1)
    try:
        page = paginator.page(p)
    except EmptyPage:
        page = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        page = paginator.page(1)


    # 显示购物车中商品的总数量, 登陆后显示,没有登陆显示为0
    cart_count = 0
    if request.session.get("ID"):
        user_id = request.session.get("ID")
        # 登陆, 从redis中取出购物车中的数据
        r = get_redis_connection("default")
        # 准备键
        cart_key = "cart_key_{}".format(user_id)
        # 取值
        cart_values = r.hvals(cart_key)
        for v in cart_values:
            cart_count += int(v)



    # 渲染数据
    context = {
        "categorys": categorys,
        # "goodsSkus": goodsSkus,
        "goodsSkus": page,
        "cate_id": cate_id,
        "order": order,
        "cart_count": cart_count,
    }
    return render(request, "sp_goods/category.html", context)


def detail(request, id):
    # id goods_sku的id
    # 只需要查询到goodssku就ok
    try:
        goodsSku = GoodsSKU.objects.get(pk=id, is_on_sale=True)
    except GoodsSKU.DoesNotExist:
        # 跳转到首页
        return redirect("sp_goods:首页")

    # 渲染数据到页面
    context = {
        "goodsSku": goodsSku
    }
    return render(request, "sp_goods/detail.html", context)

SpMarket/templates/sp_goods/category.html
{% extends 'public/base.html' %}
{% load static %}

{% block meta_css %}
    <style>
        .shop-list-mid .tit a {
            color: #909090;
            font-size: 1.4rem;
            display: -webkit-box;
            -webkit-line-clamp: 1;
            -webkit-box-orient: vertical;
            overflow: hidden;
            white-space: normal;
            text-overflow: ellipsis;
        }

        .list-price {
            background: url({% if order == 2 %}{% static 'images/order-bot.png' %}{% elif order == 3 %}{% static 'images/order-top.png' %}{% else %}{% static 'images/order.png' %}{% endif %}) no-repeat right center;
            padding-right: 20px;
            font-style: normal;
        }
    </style>
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <form action="/search/" method="get">
            <div class="cate-search">
                <input type="text" name="q" class="cate-input" placeholder="请输入您要的搜索的产品关键词"/>
                <input type="submit" value="" class="cate-btn"/>
            </div>
        </form>

    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <ul class="list-nav">
        <li {% if order == 0 %}class="current"{% endif %}><a href="{% url 'sp_goods:分类' cate_id 0 %}">综合</a></li>
        <li {% if order == 1 %}class="current"{% endif %}><a href="{% url 'sp_goods:分类' cate_id 1 %}">销量</a></li>
        <li {% if order == 2 %}class="current"{% endif %}><a href="{% url 'sp_goods:分类' cate_id 2 %}"><i
                class="list-price">价格</i></a></li>
        <li {% if order == 4 %}class="current"{% endif %}><a href="{% url 'sp_goods:分类' cate_id 4 %}">新品</a></li>
    </ul>
    <div class="content-list">
        <div class="list-left">
            {% for category in categorys %}
                <li {% if cate_id == category.pk %}class="current"{% endif %}>
                    <a href="{% url 'sp_goods:分类' category.pk order %}">{{ category.cate_name }}</a>
                </li>
            {% endfor %}
        </div>


        <div class="list-right">
            <ul class="list-pro">
                {% for goods in goodsSkus %}
                    <li>
                        <a href="{% url 'sp_goods:详情' goods.pk %}"><img src="{{ MEDIA_URL }}{{ goods.logo }}"
                                                                        class="list-pic"/></a>
                        <div class="shop-list-mid" style="width: 65%;">
                            <div class="tit">
                                <a href="{% url 'sp_goods:详情' goods.pk %}">
                                    {{ goods.goods_spu.spu_name }}&emsp;{{ goods.sku_name }}
                                </a>
                            </div>
                            <div class="am-gallery-desc">￥{{ goods.price }}</div>
                            <p>销量：{{ goods.sale_num }}{{ goods.unit }}</p>
                        </div>
                        <div class="list-cart">
                            <div class="d-stock ">
                                <a class="decrease">-</a>
                                <input id="num" sku_id="{{ goods.pk }}" readonly="" class="text_box" name="" type="text" value="0">
                                <a class="increase">+</a>
                            </div>
                        </div>
                    </li>

                {% empty %}
                    <li>该分类下没有商品!~~~</li>
                {% endfor %}
            </ul>
            {% if goodsSkus.has_previous %}
                <a href="?p={{ goodsSkus.previous_page_number }}" class="am-btn">上一页</a>
            {% endif %}
            {% if goodsSkus.has_next %}
                <a href="?p={{ goodsSkus.next_page_number }}" class="am-btn">下一页</a>
            {% endif %}

        </div>
    </div>

    <!--底部-->
    <div style="height: 55px;"></div>
    <div class="fix-bot">
        <a href="{% url 'sp_cart:index' %}"><div class="fix-bot-cart"><i id="cart_count">{{ cart_count }}</i></div></a>
        <a href="tureorder.html" class="list-js">去结算</a>
        <a href="tureorder.html" class="list-jsk">一键快购</a>
        <!--<div class="js-text">
           <p><b>￥217.80</b></p>
           <p class="js-car">购物满50元免运费</p>
     </div>-->
    </div>

{% endblock %}



{% block footer_js %}
    <script>

        $(function () {
            //改变价格上的url地址
            if ("{{ order }}" == 2) {
                $(".list-price").parent("a").attr('href', "{% url 'sp_goods:分类' cate_id 3 %}")
            } else if ("{{ order }}" == 3) {
                $(".list-price").parent("a").attr('href', "{% url 'sp_goods:分类' cate_id 2 %}")
            }
        });

        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                current_num += 1;

                //发送ajax到后台 添加购物车数据
                //收集数据 count sku_id
                var count = 1;
                var sku_id = self.siblings('input').attr('sku_id');
                //发送ajax
                $.ajax({
                    type:'post',
                    url:'{% url "sp_cart:addCart" %}',
                    data:{
                        "count":count,
                        "sku_id":sku_id,
                        "csrfmiddlewaretoken":"{{ csrf_token }}",
                    },
                    dataType:"json",
                    success:function (data) {

                        if(data.code == 0){
                            if (current_num > 0) {
                                self.siblings(".decrease").fadeIn();
                                self.siblings(".text_box").fadeIn();
                            }
                            self.siblings('input').val(current_num);

                            //更新购物车中总数量的显示
                            $("#cart_count").text(data.cart_count);

                        }else if (data.code == 1){
                            //跳转到登陆页面
                            var flag = confirm("没有登陆,是否立即登陆?");
                            if(flag){
                               location.href = "{% url 'sp_user:login' %}?next={% url 'sp_goods:分类' cate_id order %}"
                            }
                        }
                    }
                });



            });
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 0) {

                     //发送ajax到后台 添加购物车数据
                    //收集数据 count sku_id
                    var count = -1;
                    var sku_id = self.siblings('input').attr('sku_id');
                    //发送ajax
                    $.ajax({
                        type:'post',
                        url:'{% url "sp_cart:addCart" %}',
                        data:{
                            "count":count,
                            "sku_id":sku_id,
                            "csrfmiddlewaretoken":"{{ csrf_token }}",
                        },
                        dataType:"json",
                        success:function (data) {
                            if(data.code == 0){
                                current_num -= 1;
                                if (current_num < 1) {
                                    self.fadeOut();
                                    self.siblings(".text_box").fadeOut();
                                }
                                self.siblings('input').val(current_num);

                                //更新购物车中总数量的显示
                                $("#cart_count").text(data.cart_count);

                            }else if (data.code == 1){
                                //跳转到登陆页面
                                var flag = confirm("没有登陆,是否立即登陆?");
                                if(flag){
                                   location.href = "{% url 'sp_user:login' %}?next={% url 'sp_goods:分类' cate_id order %}"
                                }
                            }
                        }
                    });

                }
            });
        })

    </script>
{% endblock %}

SpMarket/templates/sp_goods/detail.html
{% extends 'public/base.html' %}
{% load static %}

{% block meta_js %}
    <script>
        function changeImage() {
            document.getElementById("imgflag").src = "{% static 'images/redherat.png' %}";
        }
    </script>
{% endblock %}

{% block meta_css %}
    <style>
        .am-slider-default .am-control-nav {
            text-align: center;
        }

        .am-slider-default .am-control-nav li a.am-active {
            background: #cb2527;
        }

        .am-slider-default .am-control-nav li a {
            border: 0;
            width: 10px;
            height: 10px;
        }
    </style>
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">商品详情</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}

{% block content %}
    <!--图片轮换-->
    <div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
        <ul class="am-slides">
            {% for g in goodsSku.gallery_set.all %}
                <li><img src="{{ MEDIA_URL }}{{ g.img_url }}"/></li>
            {% endfor %}
        </ul>
    </div>
    <div class="detal-info" style="position: relative; width: 100%;">
        <p>{{ goodsSku.goods_spu.spu_name }}&emsp;{{ goodsSku.sku_name }}</p>
        <h2>商城价：<span>￥{{ goodsSku.price }}</span></h2>
        <div class="heart">
            <img src="{% static 'images/herat.png' %}" width="25" id="imgflag" onclick="changeImage()"/>
            <p>收藏</p>
        </div>
    </div>
    <div class="d-amount">
        <h4>数量：</h4>
        <div class="d-stock">
            <a class="decrease">-</a>
            <input id="num" sku_id="{{ goodsSku.pk }}" readonly="" class="text_box" name="" type="text" value="1">
            <a class="increase">+</a>
        </div>
        <h4>{{ goodsSku.unit }}</h4>
    </div>
    <div style="background: #eee; height: 10px;"></div>
    <div class="am-tabs detail-list" data-am-tabs>
        <ul class="am-tabs-nav am-nav am-nav-tabs">
            <li class="am-active"><a href="#tab1">商品详情</a></li>
            <li><a href="#tab2">商品评论</a></li>
        </ul>

        <div class="am-tabs-bd">
            <div class="am-tab-panel am-fade am-in am-active detail " id="tab1">
                {{ goodsSku.goods_spu.content|safe }}
            </div>
            <div class="am-tab-panel am-fade detail " id="tab2">
                <ul class="comment-list">
                    <li class="current"><a href="">全部</a></li>
                    <li><a href="">好评（20）</a></li>
                    <li><a href="">中评（5）</a></li>
                    <li><a href="">差评（0）</a></li>
                </ul>
                <ul class="comment-pic">
                    <li>
                        <div class="tit">
                            <img src="{% static 'images/tx.png' %}" class="tx"/>
                            <span>songke2014</span>
                            <i> [2016-01-01]</i>
                        </div>
                        <div class="comment-con">
                            买了些给家人，都说不错！
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>


    <!--底部-->
    <div style=" height: 55px;"></div>
    <ul class="fix-shopping">
        <li><a href="javascript:;" class="join">加入购物车</a></li>
        <li><a href="tureorder.html" class="imm-buy">立即购买</a></li>
    </ul>
{% endblock %}



{% block footer_js %}
{#    {% csrf_token %}#}
    <script>
        //购物数量加减
        $(function () {
            $('.increase').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                current_num += 1;
                self.siblings('input').val(current_num);
            });
            $('.decrease').click(function () {
                var self = $(this);
                var current_num = parseInt(self.siblings('input').val());
                if (current_num > 1) {
                    current_num -= 1;
                    self.siblings('input').val(current_num);
                }
            });
            
            //绑定点击事件
            $(".join").on("click",function () {
                //将当期商品添加到当期用户的购物车中
                //获取num input 标签
                var num_input = $("#num");
                //商品sku_id
                var sku_id = num_input.attr("sku_id");
                //商品的数量count
                var count = num_input.val();

                //发送ajax 请求
                $.ajax({
                    type:"POST",
                    url:"{% url 'sp_cart:addCart' %}",
                    data:{
                        'sku_id':sku_id,
                        'count':count,
                        'csrfmiddlewaretoken':'{{ csrf_token }}'
                    },
                    dataType:"json",
                    success:function (data) {
                        if(data.code == 0){
                            alert("添加购物车成功!")
                        }else if(data.code == 1){
                            //没有登录 跳转到登陆页面
                            var flag = confirm("没有登陆,是否跳转到登陆页面");
                            if(flag){
                                //跳转
                                location.href = "{% url 'sp_user:login' %}?next={% url 'sp_goods:详情' goodsSku.pk %}"
                            }
                        }
                    }
                })
            })
        })
    </script>
{% endblock %}